apiVersion: batch/v1
kind: CronJob
metadata:
  name: countries
spec:
  schedule: "0 0 * * *" # Run once a day at 00:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: countries
            image: basesdedatos2/countries
            env:
            - name: MARIAHOST
              value: "databases-mariadb"
            - name: MARIAPORT
              value: "3306"
            - name: MARIAUSER
              value: "user"
            - name: MARIADB
              value: "weather"
            - name: MARIAPASS
              valueFrom:
                secretKeyRef:
                  name: databases-mariadb
                  key: mariadb-password
                  optional: false
          restartPolicy: OnFailure
