# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  orchestrator:
    name: producer
    output_queue: "TO_PROCESS"
    image: basesdedatos2/orchestrator
  processor:
    replicas: 10
    name: consumer
    input_queue: "TO_PROCESS"
    output_queue: "TO_PARSE" 
    image: basesdedatos2/processor
  parser:
    replicas: 1
    name: parser
    input_queue: "TO_PARSE"
    output_queue: "TO_TRANSFORM"
    image: basesdedatos2/parser'
  elements_transformation:
    replicas: 1
    name: elements_transformation
    input_queue: "TO_TRANSFORM"
    output_queue: "TO_STATION"
    image: basesdedatos2/elements_transformation'